### ISSUE TITLE
Distributions.jl dependency

### ISSUE THREAD

**Issue by karanbudhraja-uw** [harryscholes/EffectSizes.jl#16]
I'm not sure if this was something I missed during the installation, but the Distributions.jl dependency seemed to not be taken care of when using Distributions.jl. I was only able to compile it after manually adding Distributions.jl to my environment first.

Error (without adding Distributions.jl manually), Warning after adding Distributions.jl manually:

```julia> using EffectSizes
[ Info: Precompiling EffectSizes [e248de7e-9197-5860-972e-353a2af44d75]
ERROR: LoadError: ArgumentError: Package EffectSizes does not have Distributions in its dependencies:
- If you have EffectSizes checked out for development and have
  added Distributions as a dependency but haven't updated your primary
  environment's manifest file, try Pkg.resolve().
- Otherwise you may need to report an issue with EffectSizes

julia> using EffectSizes
[ Info: Precompiling EffectSizes [e248de7e-9197-5860-972e-353a2af44d75]
┌ Warning: Package EffectSizes does not have Distributions in its dependencies:
│ - If you have EffectSizes checked out for development and have
│   added Distributions as a dependency but haven't updated your primary
│   environment's manifest file, try Pkg.resolve().
│ - Otherwise you may need to report an issue with EffectSizes
└ Loading Distributions into EffectSizes from project dependency, future warnings for EffectSizes are suppressed.

**Comment by harryscholes** [comment]
I've only just seen this issue. How did you install EffectSizes? Which Julia version?

I cannot repro this issue on a fresh install of the package

```julia
(@v1.6) pkg> add EffectSizes
...

julia> using EffectSizes

julia> HedgeG
HedgeG
```

**Comment by rikhuijzer** [comment]
Distributions is clearly in `Project.toml` and I also cannot reproduce the issue. Feel free to open the issue again if it is still there for you.

**Comment by karanbudhraja-uw** [comment]
thank you for checking on this! I had gotten the error for 1.3.0 and 1.5.0. I do not get this error in a clean installation of 1.6.0, so the problem was at my end (maybe the installation environment is dirty).
